### ISSUE TITLE
running the code on mac

### ISSUE THREAD

**Issue by jkingslake** [r-barnes/Barnes2020-FillSpillMerge#23]
Hi, 
Apologies for the simplistic question, but after successfully compiling on mac (14.2.1 (23C71)) with
```
brew install gdal libomp cmake llvm
git clone --recurse-submodules -j8 https://github.com/r-barnes/Barnes2020-FillSpillMerge
cd Barnes2020-FillSpillMerge
mkdir build
cd build
cmake -D CMAKE_C_COMPILER="/opt/homebrew/Cellar/llvm/17.0.6/bin/clang" -D CMAKE_CXX_COMPILER="/opt/homebrew/Cellar/llvm/17.0.6/bin/clang++" -DUSE_GDAL=ON  -DCMAKE_BUILD_TYPE=Release ..
make
```

How do I run the code? All I see are `.exe`, which I cant run on mac. 

Furthermore, how do I define inputs, etc. 

Thanks for any help! I am really excited about applying this tool to Antarctic surface topography!

**Comment by jkingslake** [comment]
Just figured out you can just remove the extension! :facepalm:

I knew this was going to be something simple!! 

OK, closing this, apologies!

**Comment by r-barnes** [comment]
@jkingslake : Interesting! The Mac won't let you run if the file has that extension?

**Comment by jkingslake** [comment]
OK, this is weird  
```./fsm_unittests.exe``` works now
as does
```./fsm.exe kerry_test3.dem test 0.0``` (i found kerry_test3.dem [here](https://github.com/r-barnes/Barnes2019-DepressionHierarchy/blob/master/test_cases/kerry_test3.dem))

I must have been doing something wrong earlier!
