### ISSUE TITLE
Cannot compile code

### ISSUE THREAD

**Issue by KCallaghan** [r-barnes/Barnes2020-FillSpillMerge#4]
I am not able to compile this code using cmake. The cmake output is:

> -- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found NetCDF: /usr/lib/x86_64-linux-gnu/libnetcdf.so  
-- Found GDAL: /usr/lib/libgdal.so  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
CMake Error at CMakeLists.txt:25 (install):
  install TARGETS given target "dephier.exe" which does not exist in this
  directory.

>CMake Error at CMakeLists.txt:26 (install):
  install TARGETS given target "dephier_paper_tests.exe" which does not exist
  in this directory.

>-- Configuring incomplete, errors occurred!

**Comment by r-barnes** [comment]
Is this with a fresh clone of the repo?

**Comment by KCallaghan** [comment]
Yes.
